# -*- coding: utf-8 -*-
"""llm_integratation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qir5IGnaRh4QK9zWlT-A588RmXzk5b3b
"""

import openai
import os

openai.api_key = os.getenv("OPENAI_API_KEY")  

def generate_feedback(data, query):
    """Use LLM to generate feedback based on the sales data and query."""
    prompt = f"Based on the following sales data, provide insights: {data.to_json()}\n\n{query}"

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=300
    )

    return response.choices[0].message.content.strip()